version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./app.env
    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: